import pytest
from datetime import datetime, timezone
from sqlalchemy.orm import Session

from models import Transaction, DetectionWindow, AnomalyDetection

def test_create_transaction(db_session: Session):
    tx = Transaction(
        merchant_id="M123",
        amount=150.0,
        timestamp=datetime.now(timezone.utc)
    )
    db_session.add(tx)
    db_session.commit()
    
    assert tx.id is not None
    assert tx.merchant_id == "M123"

def test_create_detection_window_and_anomaly(db_session: Session):
    now = datetime.now(timezone.utc)
    
    window = DetectionWindow(
        merchant_id="M123",
        window_start=now,
        window_end=now,
        transaction_count=10,
        total_amount=1500.0,
        avg_transaction_amount=150.0,
        is_synthetic_fraud_spike=True,
        split="train"
    )
    db_session.add(window)
    db_session.commit()
    
    assert window.id is not None
    
    anomaly = AnomalyDetection(
        window_id=window.id,
        detector_type="ml",
        risk_score=95.5,
        is_flagged=True,
        explanation="High transaction count anomaly."
    )
    db_session.add(anomaly)
    db_session.commit()
    
    assert anomaly.id is not None
    assert anomaly.window_id == window.id


def test_anomaly_detection_explanation_column_type():
    """Verify AnomalyDetection.explanation is explicitly defined as SQLAlchemy Text type."""
    from sqlalchemy import Text
    column = AnomalyDetection.__table__.columns["explanation"]
    assert isinstance(column.type, Text)


def test_anomaly_detection_long_text_round_trip(db_session: Session):
    """
    Verify that multi-paragraph long explanation text (>= 2,000 chars) survives
    a full ORM write and read cycle without truncation or corruption.
    """
    now = datetime.now(timezone.utc)
    window = DetectionWindow(
        merchant_id="merchant_001",
        window_start=now,
        window_end=now,
        transaction_count=42,
        total_amount=95000.0,
        avg_transaction_amount=2261.9,
        is_synthetic_fraud_spike=True,
        split="dev_test",
    )
    db_session.add(window)
    db_session.commit()

    # Construct multi-paragraph explanation with >= 2,000 characters
    long_explanation = (
        "ANOMALY EXPLANATION REPORT (Merchant: merchant_001, Window: 101)\n"
        "========================================================================\n\n"
        "1. EXECUTIVE SUMMARY:\n"
        "A severe fraud-spike anomaly was flagged for merchant merchant_001 during the evaluated 1-hour tumbling window. "
        "The composite anomaly severity score reached 75.0/100, placing this merchant window into the HIGH risk band. "
        "Estimated financial exposure is calculated at ₹47,500.00, representing 50.0% of the total window volume. "
        "Immediate human review and escalation for priority review is strongly recommended.\n\n"
        "2. DETAILED QUANTITATIVE ANOMALY DRIVERS:\n"
        "- Transaction Count Driver: Observed 42 transactions in the 1-hour tumbling window, surging to 4.2x (+320.0%) "
        "above the merchant's historical baseline mean of 10.0 transactions per window. This elevated transaction frequency "
        "strongly indicates automated card-testing, scripted batch submissions, or an active distributed attack vector.\n"
        "- Monetary Volume Driver: Total processed volume reached ₹95,000.00, representing a 3.8x (+280.0%) surge above "
        "the historical baseline mean of ₹25,000.00. The monetary acceleration corresponds with rapid transaction bursts.\n"
        "- Average Ticket Size: Ticket size averaged ₹2,261.90, which remains consistent with standard merchant pricing "
        "structures but aggregates into substantial exposure due to high transaction velocity.\n\n"
        "3. AUDIT TRAIL AND DEFENSIVE ACTION PLAN:\n"
        "In accordance with defense-only operational policies, automated account termination, freezing, or blocking is "
        "strictly disabled. Human fraud analysts should inspect the recent transaction batch, verify cardholder authorization "
        "patterns, review geographical concentration of IP addresses, and initiate contact with the merchant if necessary.\n\n"
        "4. METHODOLOGY AND COMPLIANCE NOTICE:\n"
        "All calculations were generated using defensible statistical baselines and verified Isolation Forest anomaly models. "
        "This evaluation utilizes synthetic transaction streams exclusively for risk management assessment. "
        "Report generated by AI Risk Manager Explanation Engine with full numerical grounding verification.\n"
    )

    # Ensure length is well above 2,000 characters
    assert len(long_explanation) >= 2000

    anomaly = AnomalyDetection(
        window_id=window.id,
        detector_type="ml",
        risk_score=75.0,
        is_flagged=True,
        explanation=long_explanation,
    )
    db_session.add(anomaly)
    db_session.commit()

    # Re-query by ID in a fresh query
    retrieved = db_session.query(AnomalyDetection).filter_by(id=anomaly.id).first()
    assert retrieved is not None
    assert retrieved.explanation == long_explanation
    assert len(retrieved.explanation) == len(long_explanation)

